services:
  mysql-server:
    image: mysql:${MYSQL_IMAGE_TAG}
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - TZ=Asia/Manila
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    networks:
      - pla-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  pla-network:
    name: ${NETWORK_NAME}
    external: false
    ipam:
      driver: default